### PR TITLE
Fixing the greek version of hello world!

### PR DESCRIPTION
**Pull request by costashatz**
There's a small typo in the greek version of hello world! ;)

### CODE REVIEW

**Comment by mosra** [comment]
Hey, wow, thank you! :)

**Comment by costashatz** [comment]
Easy for me; I am Greek! :stuck_out_tongue:

**Comment by mosra** [comment]
I should have asked you for the correct version in the first place, back when I was creating this demo :D 

What did it mean, anyway?

**Comment by costashatz** [comment]
The original one was saying (with a small grammar error): "Hello you, the world!" 

The new one says exactly: "Hello world!"

Btw, you can update the png in this repo and the magnum website (showcase part)..  I could do the first part if you don't have time; I think it's better if you do the second.. :D

**Comment by mosra** [comment]
Yeah, it's on my TODO list for today :) I'm doing various updates to documentation of all other examples, so this will get done along the way.

**Pull request merged**
