### PR TITLE
Add fluid simulation example

### PR DESCRIPTION
**Pull request by ttnghia**
Finally, fluid simulation example for magnum :heart_eyes:
Please make a WebGL example of this. I don't know how to do it now :)
Let me know if there's anything needs to be changed.

image

### CODE REVIEW

**Comment by mosra** [comment]
Yay, Xmas come early this year! I need to try this out immediately :)

**Comment by alanjfs** [comment]
The [ThreadPool stuff](https://github.com/mosra/magnum-examples/pull/69/files#diff-2ef054fd63a909c8c7712f0e5a35f88d) is super interesting. :O Thanks for sharing this!

**Comment by alanjfs** [comment]
Adding a gif, for easy sharing. :)

- https://vimeo.com/368947792

**Comment by ttnghia** [comment]
I just pushed new changes:
[X] Add back tbb code.
[X] Limit 60FPS rendering but maximize computation: run a number of simulation steps (which is dynamically computed) per frame.

**Comment by mosra** [comment]
Thank you, this is great :+1: 

Sorry for the lack of action on my side, got a priority thing to work on right now. I'll try to get this merged later this week.

**Comment by mosra** [comment]
Merged as 4fb94bd7b8e9f97dce9e94b3bc4100dbf12cd45c and ba5000c32329e1c758d3d405f9ffa90f90fe25d1 -- you did some great work, thanks a lot :+1: I didn't look into the WebGL port yet, hopefully soon :)

Docs for the example are at https://doc.magnum.graphics/magnum/examples-fluidsimulation3d.html -- I was not sure what exactly to put there, so if you have some further information, let me know.

**Pull request closed without merging**
