### PR TITLE
ovr: Adapt to LibOvrIntegration API changes.

### PR DESCRIPTION
**Pull request by Squareys**
Hi @mosra!

Corresponding to mosra/magnum-integration#5, here are the adaptations for the ovr example.

Greetings, 
Squareys.

### CODE REVIEW

**Comment by Squareys** [comment]
The last commit obviously doesn't fit this pullrequest thematically, I hope that's okay. Was only a one line fix ;)

**Comment by mosra** [comment]
No worry about that (and good catch!).

**Comment by mosra** [comment]
By the way, did the deprecated header produce a warning for you or not? I suspect that the deprecation warnings are broken somehow...

**Comment by Squareys** [comment]
No, it did, when you build without deprecated.

**Comment by mosra** [comment]
Merged. Looks like the deprecation warnings are somehow not shown as GCC treats the includes as system ones (for which all warnings are disabled). Weird, I need to investigate further.

**Pull request merged**
