### PR TITLE
Add examples to a common folder in visual studio

### PR DESCRIPTION
**Pull request by TrevorCash**
Groups examples in a common folder on visual studio

### CODE REVIEW

**Comment by mosra** [comment]
Thank you! Yeah I was lazy and did this for all other repositories except this one :)

I don't use VS myself and don't really remember how the project tree looks there but ... isn't grouping of all examples together too coarse? Or does VS itself make subfolders based on the executable?

If it makes subfolders then it's probably fine like this, and it'd be enough to have just a single

```cmake
# IDE folder in VS, Xcode etc. CMake 3.12+, older versions have only the FOLDER
# property that would have to be set on each target separately.
set(CMAKE_FOLDER "MagnumExamples")
```

at the top of `src/CMakeLists.txt`. That'd do it the same way as in other projects.

**Comment by TrevorCash** [comment]
As it is, it ends up creating 1 folder with all the example projects inside.

**Comment by mosra** [comment]
Can you screenshot it for me? :) Just so I have an idea how it looks like and how much worse it would get for VS in case someone would want subfolders instead. The `FOLDER` property is also doing similar grouping in Xcode, and there it behaves a bit different IIRC.

Thank you!

**Comment by TrevorCash** [comment]
Heres my solution: (4 examples enabled) image

**Comment by mosra** [comment]
Pushed as 74496c1695fd3563750f4c5e2fda0126865e255f, the loose `MagnumPlugins-headers` target is fixed in mosra/magnum-plugins@7a438d0bd8ab4610c4f4d224cd332e5cc91bc067.

Thank you!

**Pull request closed without merging**
